spring:
  application:
    name: customer-products-and-services

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      dll-auto: update
      format_sql: true

  h2:
    console:
        enabled: true
        path: /h2-console

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

